# -*- coding: utf-8 -*-
"""getData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SPBM26k-fItsxAcVO8A3XhPoS-Dq_Pn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

calTax = pd.read_csv("7nwe-3aj9.csv")
calTax = calTax.T
calTax.to_csv("data/clean.csv", index=False)
calTax = calTax.T
calTax["year"] = pd.to_datetime(calTax["year"], format="%Y")
propCal = calTax[calTax['locationabbr']=="CA"][0:1836]
propCal.T

